In [13]:
# Import the dependencies.
import pandas as pd #to read our CSV file and create the locations and measurements from the DataFrame.
import gmaps #to create heatmaps and the locations map
import requests #to make a request to the Google Places JSON file. This will allow us to get hotel locations from the latitude and longitude of the city.

# Import the API key.
from config import g_key #to create heatmaps and the locations map
#import os
#g_key = os.environ.get('gkey')

In [20]:
#print(g_key)

In [15]:
#read our cities.csv file into a DataFrame

# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Kavaratti,IN,2021-01-19 16:59:37,10.5669,72.6420,82.27,66,2,1.52
1,1,Champerico,GT,2021-01-19 16:59:37,14.3000,-91.9167,86.00,58,0,5.97
2,2,Camacha,PT,2021-01-19 16:59:37,33.0833,-16.3333,64.40,63,20,5.75
3,3,Sorland,NO,2021-01-19 16:59:38,67.6670,12.6934,35.60,64,0,16.11
4,4,Carnarvon,AU,2021-01-19 16:59:38,-24.8667,113.6333,78.80,89,0,16.11

In [16]:
#Confirm the data types for the data columns are integers or floating-point decimal numbers.
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [17]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [18]:
#Google heatmaps do not plot negative numbers. 
#If you have a maximum temperature that is less than 0 °F, then you will get an InvalidWeightException error for this line of code: heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)
#To remove the negative temperatures we can use a for loop to iterate through the max_temp and add the temperatures that are greater than 0 °F to a new list.

# Get the maximum temperature.
#max_temp = city_data_df["Max Temp"]
#temps = []
#for temp in max_temp:
    #temps.append(max(temp, 0)) #Using the max() function to get the largest value between the temp and 0. If the temp is less than 0, then 0 will be added to the list in its place. Otherwise, the temp is added to the list.

In [24]:
#create the heatmap for the maximum temperature

# Heatmap of temperature

# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.
max_temp = city_data_df["Max Temp"] # an array of length equal to the locations array length

# Assign the figure variable to the gmaps.figure() attribute.
fig = gmaps.figure()

# Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
#OPTION 1
#heat_layer = gmaps.heatmap_layer(locations, weights=temps)
#OPTION 2: INSTEAD OF USING THE FOR LOOP IN THE CELL ABOVE:   for temp in max_temp: temps.append(max(temp, 0))
#heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)

#Add the geographic center of Earth in the form of latitude and longitude (30.0° N and 31.0° E). 
#Add a zoom level so that only one map of Earth is shown
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Add the heatmap layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [28]:
#Create a Percent Humidity Heatmap
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [31]:
#Create a Percent Cloudiness Heatmap
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
cloudiness = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=cloudiness, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [32]:
#Create a Wind Speed Heatmap
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [33]:
#write two input statements for the app that will prompt the customer to add minimum and maximum temperature values and convert these values to floating-point decimals
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [63]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Kavaratti,IN,2021-01-19 16:59:37,10.5669,72.6420,82.27,66,2,1.52
1,1,Champerico,GT,2021-01-19 16:59:37,14.3000,-91.9167,86.00,58,0,5.97
4,4,Carnarvon,AU,2021-01-19 16:59:38,-24.8667,113.6333,78.80,89,0,16.11
11,11,Mar Del Plata,AR,2021-01-19 16:59:39,-38.0023,-57.5575,75.20,60,0,14.97
12,12,Hambantota,LK,2021-01-19 16:59:39,6.1241,81.1185,78.84,83,37,1.19

In [37]:
#determine if there are any null values
preferred_cities_df.count()

City_ID       149
City          149
Country       148
Date          149
Lat           149
Lng           149
Max Temp      149
Humidity      149
Cloudiness    149
Wind Speed    149
dtype: int64

In [38]:
preferred_cities_df.isnull().sum()

City_ID       0
City          0
Country       1
Date          0
Lat           0
Lng           0
Max Temp      0
Humidity      0
Cloudiness    0
Wind Speed    0
dtype: int64

In [61]:
#Drop null cells
preferred_cities_df = preferred_cities_df.dropna()

In [62]:
#determine if there are any null values
preferred_cities_df.count()

City_ID       148
City          148
Country       148
Date          148
Lat           148
Lng           148
Max Temp      148
Humidity      148
Cloudiness    148
Wind Speed    148
dtype: int64

In [64]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

             City Country  Max Temp      Lat       Lng Hotel Name
0       Kavaratti      IN     82.27  10.5669   72.6420
1      Champerico      GT     86.00  14.3000  -91.9167
4       Carnarvon      AU     78.80 -24.8667  113.6333
11  Mar Del Plata      AR     75.20 -38.0023  -57.5575
12     Hambantota      LK     78.84   6.1241   81.1185
18      Mount Isa      AU     84.20 -20.7333  139.5000
22      Caravelas      BR     84.52 -17.7125  -39.2481
28         Avarua      CK     82.40 -21.2078 -159.7750
31        Rikitea      PF     77.95 -23.1203 -134.9692
35        Ipameri      BR     82.96 -17.7219  -48.1597

In [65]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [75]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()

hotels

{'html_attributions': [],
 'next_page_token': 'ATtYBwLJUnyRw7vRxDU6I1M0pG4GghqFK4EHk7gHk97Z0vQV0ZmsdI5-fGvRyTFOwROQgzMpfHBwQiyht84HHVUZlYoNLNOV32DdTK5ffSkXOHp59zv1oCKICv4RcwgmH4cImHeNlv7yl0fbBbmuMoLxVkQw90Xm0TwnLPozWKlthCdVNon_ertC2D4RKydUe3FWNCqIKaJWzW78NZ2I3ujJQIg3SSunpNZDHDmpE70zQVJ9gIIujGoyOUvolesO0qAUq62bbzdVo3gS54o6M3DZH28uBDSB-GluBpIxkm0c2hVx9ebUKkm68pgJlPVY-BP9EXJq89cMHJOe7j7Znst3C1pGWkz1NZocSteDLGnnnTWwRtaP_Aq5FzZSSw656Zsdgdd5Zt_9cPDEYNeab4_g-CiK8jyqsrIziusBKU5whFrhx7nOouKVHgpz',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8581126, 'lng': 2.3529277},
    'viewport': {'northeast': {'lat': 48.8594393802915,
      'lng': 2.354352980291502},
     'southwest': {'lat': 48.8567414197085, 'lng': 2.351655019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Hôtel Duo',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107554201425443337224">Hôtel Duo</a>'],
     'photo_reference': 'ATtYBwLR0bRjZ0DgJAJRIKyOhejl9iJ6n14Ho9xPfmI7tGgSM0TxvfyQMtwsgHGDR5_dhyfhVBoSqaK6rs2P9B3R0sKT5i0EyNwYnSkKoYqYlKe19DscZbkpNj9M6MK8htQVKkcMgTE3546PJnLBBiBKCKxIDhKJ_kssC6UyIfFvl-ypPn3Y',
     'width': 5760}],
   'place_id': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'plus_code': {'compound_code': 'V953+65 Paris, France',
    'global_code': '8FW4V953+65'},
   'rating': 4.2,
   'reference': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'scope': 'GOOGLE',
   'types': ['night_club',
    'spa',
    'lodging',
    'bar',
    'gym',
    'health',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 278,
   'vicinity': '11 Rue du Temple, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8582861, 'lng': 2.3464944},
    'viewport': {'northeast': {'lat': 48.8595495802915,
      'lng': 2.347780980291502},
     'southwest': {'lat': 48.8568516197085, 'lng': 2.345083019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Hôtel Britannique',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 546,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108984000175492464929">Hôtel Britannique - Paris Louvre</a>'],
     'photo_reference': 'ATtYBwKlP5OfoaY8-DryEzpwJtem-uWzR05LX83jouee01QNb2eKnK3SOjEUWXhslg6rne2yLKkiXptkyRkSEjclZBY4RiZB3GXosAs8GaO5ZiO90yLUE9aV1-FRWP2g0trWCIpx8HjD3oRWcVk872c5lGiyrZdD_yZ42hEZvlWOV-bJenBB',
     'width': 1024}],
   'place_id': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'plus_code': {'compound_code': 'V85W+8H Paris, France',
    'global_code': '8FW4V85W+8H'},
   'rating': 4.6,
   'reference': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 418,
   'vicinity': '20 Avenue Victoria, Paris'},
  {'business_status': 'CLOSED_TEMPORARILY',
   'geometry': {'location': {'lat': 48.8606655, 'lng': 2.3469293},
    'viewport': {'northeast': {'lat': 48.8618387802915,
      'lng': 2.348475730291502},
     'southwest': {'lat': 48.85914081970851, 'lng': 2.345777769708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Citadines Les Halles Paris (Apart Hotel Paris)',
   'permanently_closed': True,
   'photos': [{'height': 496,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102565262508115704337">Citadines Les Halles Paris (Apart Hotel Paris)</a>'],
     'photo_reference': 'ATtYBwIXlb2J-0zYk0EhP8eo9dRpgrgIN2MPkHdscetKq2mdyGivDOSA_1JBMqpZiw06-ZCLDboAQCJPOorAXkcbIhShFkkh3B12V9MH3fQ84sGHTJqrhSIbq--3aP2swiPz8bGXzAlc0nbhhCjLCPUAy5w8ab1s_JEjx9aNUgK_lhNS7Oe3',
     'width': 745}],
   'place_id': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'plus_code': {'compound_code': 'V86W+7Q Paris, France',
    'global_code': '8FW4V86W+7Q'},
   'rating': 4.1,
   'reference': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 817,
   'vicinity': '4 Rue des Innocents, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8607769, 'lng': 2.3463217},
    'viewport': {'northeast': {'lat': 48.8620135802915,
      'lng': 2.347597080291502},
     'southwest': {'lat': 48.8593156197085, 'lng': 2.344899119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Novotel Paris Les Halles',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111815616573299411056">Novotel</a>'],
     'photo_reference': 'ATtYBwL4gJv0QaasVI2zs5lAA-WOJlHH9BSpjkjV4BUYbmo0OHP2pGdkufaVeph7eBhB9VkHAOIsgNDvtsVOFYVtqyVbFzJUfDDm3lwmHc_WSvgQRjtL14v9sNifhvOaGEZZfhGrzphuTBvlOdJS9Qpek6-wqUoxSE9luMFuxQp90Ru5TNTU',
     'width': 3000}],
   'place_id': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'plus_code': {'compound_code': 'V86W+8G Paris, France',
    'global_code': '8FW4V86W+8G'},
   'rating': 4.4,
   'reference': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2090,
   'vicinity': '8 Place Marguerite de Navarre, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86034799999999, 'lng': 2.344054},
    'viewport': {'northeast': {'lat': 48.8616503302915,
      'lng': 2.345521080291502},
     'southwest': {'lat': 48.8589523697085, 'lng': 2.342823119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Hôtel Ducs de Bourgogne',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1390,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101411638353598558320">Best Western Premier Ducs de Bourgogne</a>'],
     'photo_reference': 'ATtYBwIRnqHlzHCkC12UT4nvlq8kgm3BQrZNkt5Bh6yrCf6cCcAUhzFYTUbNqwnH12fRo-1BctRtNgpQGJyfMcnGbWzvi7Gt0QJ0FMqsA1NLk612w8ag489c4nPt_HO3w3YIemsCRr2L3b7znG1t6uf8NZtUprnTrLRZ7B5XpzhjzSDCss6P',
     'width': 2048}],
   'place_id': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'plus_code': {'compound_code': 'V86V+4J Paris, France',
    'global_code': '8FW4V86V+4J'},
   'rating': 4.5,
   'reference': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 275,
   'vicinity': '19 Rue du Pont Neuf, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8555091, 'lng': 2.3408736},
    'viewport': {'northeast': {'lat': 48.8569076302915,
      'lng': 2.342319280291502},
     'southwest': {'lat': 48.8542096697085, 'lng': 2.339621319708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Citadines Saint-Germain-des-Prés Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107856881779358840274">David O&#39;Meara</a>'],
     'photo_reference': 'ATtYBwJBvBmglnQX1u9dUYDAkLLI9MFqWNiZhBJvWUAFMxZn-kmwdc970IyzIKBCgP1EJmTZmjx54mek1-Hyk1N6LhlQOcorDCCcgftSu-MhEHp1uvJ9B0pcjtRitoZJKJTpo64CiQ2-yMPBoZDm7GIXLTRv_2uM3azHPqDNogXhoQJGdb-2',
     'width': 4032}],
   'place_id': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'plus_code': {'compound_code': 'V84R+68 Paris, France',
    'global_code': '8FW4V84R+68'},
   'rating': 4.3,
   'reference': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 652,
   'vicinity': '53 ter Quai des Grands Augustins, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86634659999999, 'lng': 2.36064},
    'viewport': {'northeast': {'lat': 48.8677623302915,
      'lng': 2.361952180291502},
     'southwest': {'lat': 48.86506436970851, 'lng': 2.359254219708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Paris France Hôtel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2673,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102332962500946068613">Paris France Hôtel</a>'],
     'photo_reference': 'ATtYBwLtJ9GZx2KUB1Qw1F_sMb1_S3sdaVlVzjn8TrxMnES6g1mvjkBWJTolaHx2PjZv_GeqJBFowGG_UxRCD1RMmqhHz8qDibiTnVSkcwu4zAwxHRqe2ARQYYQP2l51KAxeUDM4NPfSCCqMyhwawfep6HL-v5thFvY3dseBTNU4j5z8hBf4',
     'width': 3463}],
   'place_id': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'plus_code': {'compound_code': 'V986+G7 Paris, France',
    'global_code': '8FW4V986+G7'},
   'rating': 4.3,
   'reference': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 375,
   'vicinity': '72 Rue de Turbigo, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86386539999999, 'lng': 2.3325488},
    'viewport': {'northeast': {'lat': 48.8652309302915,
      'lng': 2.333762030291502},
     'southwest': {'lat': 48.8625329697085, 'lng': 2.331064069708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Hotel Regina Louvre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3700,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109908333790946649027">Hôtel Regina Louvre</a>'],
     'photo_reference': 'ATtYBwKJIiLR504yzw3hukkqrxKmDM9xKgUaoua6pQ25O1kDErCjoLeZc9L1WyFhES7qkX5uHwL1uj4MbFFVKGtx4YWvHb1Rlnm6aLNPy_qAQAHMpDQKWp7pKa6cnF7xcIzXC07eu0aHakGp9NOwusCh-pJna4laPqf_X6dyb4XSouTFB7PS',
     'width': 5550}],
   'place_id': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'plus_code': {'compound_code': 'V87M+G2 Paris, France',
    'global_code': '8FW4V87M+G2'},
   'rating': 4.5,
   'reference': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 504,
   'vicinity': '2 Place des Pyramides, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84795229999999, 'lng': 2.370869},
    'viewport': {'northeast': {'lat': 48.84922153029149,
      'lng': 2.372321980291502},
     'southwest': {'lat': 48.84652356970849, 'lng': 2.369624019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'ibis Paris Gare de Lyon Ledru Rollin 12ème',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102166088584622554231">cherry pyj</a>'],
     'photo_reference': 'ATtYBwJQT_TjjsoFtlhA0CRCeMQ3RHoWvZ5TbBq8QojyXcS7kpxDafqUZA7l80mSiW6PSuez6KMi4Co8BEzXXfKqkKjVkXEqJgfKQ0wxraVeAUddESoxA1RozrUEwDdzkz8rHZ9mwbUTeSQFPudwvbd2MIo2PLA9WEYYEnEnzjvybGZoCtwW',
     'width': 4032}],
   'place_id': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'plus_code': {'compound_code': 'R9XC+58 Paris, France',
    'global_code': '8FW4R9XC+58'},
   'rating': 4,
   'reference': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 748,
   'vicinity': '41/43 Avenue Ledru Rollin, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8475464, 'lng': 2.3718722},
    'viewport': {'northeast': {'lat': 48.8488750302915,
      'lng': 2.373125480291502},
     'southwest': {'lat': 48.8461770697085, 'lng': 2.370427519708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Hôtel De France Gare de Lyon Bastille',
   'photos': [{'height': 1960,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104045426349853231072">michael scanlon</a>'],
     'photo_reference': 'ATtYBwLSt6xwmh2rshBM44C4HT2vpHnHxgeXgMd0UrYdHmsyhNv1jM3nWK8i2ZyQIwrmJWRUYiCLLF7yFcvmCRNTOrM4IlasxBJzXaWtcM8pM_5uB25foh_K2TtmV31h3RQjEud4uwi2fY4CoAFCBjOlx-svvm4gvyy1X337BwxEMWKFtPoa',
     'width': 4032}],
   'place_id': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'plus_code': {'compound_code': 'R9XC+2P Paris, France',
    'global_code': '8FW4R9XC+2P'},
   'rating': 3.3,
   'reference': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 380,
   'vicinity': '12 Rue de Lyon, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8717386, 'lng': 2.3447052},
    'viewport': {'northeast': {'lat': 48.8731394302915,
      'lng': 2.346067130291502},
     'southwest': {'lat': 48.8704414697085, 'lng': 2.343369169708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Hôtel Prélude Opéra',
   'photos': [{'height': 4000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/110158133027602673318">Marisa Pretto</a>'],
     'photo_reference': 'ATtYBwIRGlyOGUTRso4cukVkOkTIEGffqvkh613e5k9BTVXYXSYKTZlQ4c3ntOx1nmICFdticg6EHYOrfLRM_uM4o0FyttyEPLNkb4AC4_hHy3F-mqu0LdqKVYe451reVsjDXAAI6xaub-N18redrwPL3X6OG7veNoQU0Bxkx8Ko3VZQN5vv',
     'width': 3000}],
   'place_id': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'plus_code': {'compound_code': 'V8CV+MV Paris, France',
    'global_code': '8FW4V8CV+MV'},
   'rating': 4,
   'reference': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 314,
   'vicinity': '8 Cité Bergère, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8423491, 'lng': 2.3632246},
    'viewport': {'northeast': {'lat': 48.84365308029151,
      'lng': 2.364707180291502},
     'southwest': {'lat': 48.84095511970851, 'lng': 2.362009219708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Hôtel Libertel Austerlitz Jardin des Plantes',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114802271282641766772">Hôtel Libertel Austerlitz Jardin des Plantes</a>'],
     'photo_reference': 'ATtYBwKJvbXy8RWz3YHKduwcwI8OcU3FiItGMXodyZ__j4ifLLXeQ-Nl5UC869U-_Gxlr842seYWdkyvVgYJSllrSMzszVQ1OlblwBrDnWTOENYufen3x-jzWDgtYzeA8zjiIFkl4D3BXXokh05SOddYLN26odclBSx2Hu6J7xHUtLRpkQjX',
     'width': 6720}],
   'place_id': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'plus_code': {'compound_code': 'R9R7+W7 Paris, France',
    'global_code': '8FW4R9R7+W7'},
   'rating': 4,
   'reference': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 433,
   'vicinity': "12 Boulevard de l'Hôpital, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.864294, 'lng': 2.3307997},
    'viewport': {'northeast': {'lat': 48.8655898302915,
      'lng': 2.332108780291502},
     'southwest': {'lat': 48.8628918697085, 'lng': 2.329410819708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Saint James Albany Paris Hôtel Spa',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1365,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108570400659068256718">Saint James Albany Paris Hôtel Spa</a>'],
     'photo_reference': 'ATtYBwLLl5HRefz_TMXF635inHMC0a3AWx934RU5pYhGNwjE_kfTtXHRpyPAxNKMtWL8o_gpBR78ls5F0BZ2sIV47DD4TadOLnuBmmWr3uX1vqSpEWrxoZZzFC18NEcp_bG7rW-xJCNGfrrKbUnVPuVMB_OBBj1T76tJI0hzH4JPc8n4xaZQ',
     'width': 2048}],
   'place_id': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'plus_code': {'compound_code': 'V87J+P8 Paris, France',
    'global_code': '8FW4V87J+P8'},
   'rating': 4,
   'reference': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 1073,
   'vicinity': '202 Rue de Rivoli, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.87110329999999, 'lng': 2.3389728},
    'viewport': {'northeast': {'lat': 48.8724296802915,
      'lng': 2.340311380291502},
     'southwest': {'lat': 48.8697317197085, 'lng': 2.337613419708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'Hôtel Icône',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1066,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108137830440312077288">Hôtel Icône</a>'],
     'photo_reference': 'ATtYBwIcvxt8d2HhWpisGjhVIhq4qdGjfesmYHLjR8N915sMeujWJ6QZNPPAOiHCFxc5nzHnge8RkceyNqQ6xqVDRhoQvZV0u3DFpJUqLHHPTm8Y85nD1fxf_KJdtpy4bALr_OaZ_lLyyrUb9mfi0JR5sJBhuTD_AxbFMmuX6Y4LBbpcCBN_',
     'width': 1600}],
   'place_id': 'ChIJpQvq5Dtu5kcR0COam2f7v_I',
   'plus_code': {'compound_code': 'V8CQ+CH Paris, France',
    'global_code': '8FW4V8CQ+CH'},
   'rating': 3.7,
   'reference': 'ChIJpQvq5Dtu5kcR0COam2f7v_I',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 135,
   'vicinity': "4 Rue d'Amboise, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8654924, 'lng': 2.3271121},
    'viewport': {'northeast': {'lat': 48.8667867302915,
      'lng': 2.328593580291502},
     'southwest': {'lat': 48.8640887697085, 'lng': 2.325895619708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': 'The Westin Paris - Vendôme',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 810,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/105819208076758962074">The Westin Paris - Vendôme</a>'],
     'photo_reference': 'ATtYBwKI7nO0cxuYzRXY4btsaTB5kOMAAMbubIYawMjOSC5-bRv7UYeimtF7pJHV1qazkYxloGz54igaFN6XYEnHlVB7PcUkaqGIe6YqmAvbjqDt2KCffoiXdyAZ32iXILHckYCQR7WrFdgfxHSwwgqwPx6okKL4SyFae8qt9UvysB8OMFml',
     'width': 1440}],
   'place_id': 'ChIJt4LY5C1u5kcRvVeuJebPxHc',
   'plus_code': {'compound_code': 'V88G+5R Paris, France',
    'global_code': '8FW4V88G+5R'},
   'rating': 4.4,
   'reference': 'ChIJt4LY5C1u5kcRvVeuJebPxHc',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2042,
   'vicinity': '3 Rue de Castiglione, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86038899999999, 'lng': 2.323112},
    'viewport': {'northeast': {'lat': 48.8617804302915,
      'lng': 2.324489280291502},
     'southwest': {'lat': 48.8590824697085, 'lng': 2.321791319708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'name': "Hôtel d'Orsay",
   'opening_hours': {'open_now': True},
   'photos': [{'height': 768,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115556676131195822021">Hôtel 4 étoile d&#39;Orsay Paris 7ème</a>'],
     'photo_reference': 'ATtYBwLbX8F7xcEpWjO9uxNcNg-IBQPVy5f8T_9IL1F90--F7l9xAlEkNRwbbyjxo3v4ElggUU9dg7clrZRaxGWK6SmnxNC9CQa7-cnh-z44OFDRV9PUGbnBtUkesdM2kqx5auJ5EUos_P9pj3kT-JXh7WCax0wcRMErZwEsKhjjpMcHLatb',
     'width': 1152}],
   'place_id': 'ChIJu39_OCtu5kcRWVQ7SFa0J-k',
   'plus_code': {'compound_code': 'V86F+56 Paris, France',
    'global_code': '8FW4V86F+56'},
   'rating': 4.6,
   'reference': 'ChIJu39_OCtu5kcRWVQ7SFa0J-k',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 207,
   'vicinity': '93 Rue de Lille, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8661363, 'lng': 2.3260648},
    'viewport': {'northeast': {'lat': 48.8674534302915,
      'lng': 2.327513280291502},
     'southwest': {'lat': 48.8647554697085, 'lng': 2.324815319708498}}},

In [76]:
#get the length of the results dictionary
len(hotels["results"])

20

In [78]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
maps_response = requests.get(base_url)
print(maps_response.status_code)

200

In [105]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()

    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [98]:
hotels["results"][0]["name"]

'Hotel Vitória Palace'

In [86]:
hotels["results"][1]["name"]

'Quartier'

In [101]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Kavaratti,IN,82.27,10.5669,72.6420,Hotels in Lakshadweep Islands
1,Champerico,GT,86.00,14.3000,-91.9167,"Hotel y restaurante ""El Diamante"""
4,Carnarvon,AU,78.80,-24.8667,113.6333,Hospitality Carnarvon
11,Mar Del Plata,AR,75.20,-38.0023,-57.5575,Gran Hotel Mar del Plata
12,Hambantota,LK,78.84,6.1241,81.1185,Bungalow 63
...,...,...,...,...,...,...
521,Male,MV,82.40,4.1748,73.5089,Hotel Octave Maldives
523,Balabac,PH,80.13,7.9868,117.0645,Sing and Swing Lodge
524,Tandil,AR,89.01,-37.3217,-59.1332,HOSTAL DE LA SIERRA TANDIL
528,Port-Gentil,GA,84.20,-0.7193,8.7815,Fengshui Residence
532,Vila Velha,BR,88.00,-20.3297,-40.2925,Hotel Vitória Palace

In [106]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [107]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [108]:
#add a pop-up marker for each city that displays the hotel name, city name, country, and maximum temperature.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [109]:
#Next, add the data to the code by iterating through the hotel_df DataFrame using the iterrows() function.
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

#Then add the information to the gmaps.marker_layer() attribute with the locations.
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))